import { bytesToBase64Url, base64UrlToBytes } from '@/domain/sync';

/**
 * DEC-103/107: end-to-end encryption for everything that crosses the
 * signaling room. The AES-GCM key is generated by the session host, travels
 * inside the QR code, and is never sent to the worker.
 */

export async function generateSessionKey(): Promise<string> {
  const key = await crypto.subtle.generateKey({ name: 'AES-GCM', length: 256 }, true, [
    'encrypt',
    'decrypt',
  ]);
  const raw = await crypto.subtle.exportKey('raw', key);
  return bytesToBase64Url(new Uint8Array(raw));
}

export async function importSessionKey(encodedKey: string): Promise<CryptoKey> {
  // Pass an exact, ArrayBuffer-backed copy of the key bytes. Node 20's stricter
  // WebCrypto rejected the previous `bytes.buffer` (a pooled/SharedArrayBuffer-
  // typed buffer that could also expose slack bytes beyond the view); `.slice()`
  // yields a fresh Uint8Array<ArrayBuffer> — a valid BufferSource that types
  // cleanly and works identically in the browser. (D-BUG-24)
  const bytes = base64UrlToBytes(encodedKey);
  return crypto.subtle.importKey('raw', bytes.slice(), { name: 'AES-GCM' }, false, [
    'encrypt',
    'decrypt',
  ]);
}

const IV_LENGTH_BYTES = 12;

export async function encryptText(key: CryptoKey, plaintext: string): Promise<string> {
  const iv = crypto.getRandomValues(new Uint8Array(IV_LENGTH_BYTES));
  const ciphertext = await crypto.subtle.encrypt(
    { name: 'AES-GCM', iv },
    key,
    new TextEncoder().encode(plaintext),
  );
  const combined = new Uint8Array(IV_LENGTH_BYTES + ciphertext.byteLength);
  combined.set(iv, 0);
  combined.set(new Uint8Array(ciphertext), IV_LENGTH_BYTES);
  return bytesToBase64Url(combined);
}

export async function decryptText(key: CryptoKey, encoded: string): Promise<string | null> {
  try {
    const combined = base64UrlToBytes(encoded);
    const iv = combined.subarray(0, IV_LENGTH_BYTES);
    const ciphertext = combined.subarray(IV_LENGTH_BYTES);
    const plaintext = await crypto.subtle.decrypt(
      { name: 'AES-GCM', iv: iv.slice() },
      key,
      ciphertext.slice(),
    );
    return new TextDecoder().decode(plaintext);
  } catch {
    return null;
  }
}

/**
 * DEC-342/343 (G5): binary E2E for image blobs. Identical AES-GCM + 12-byte
 * IV-prefix scheme as `encryptText`, but the IO is raw bytes — the ciphertext is
 * uploaded to R2 as `application/octet-stream` (no base64 bloat on the wire).
 * The key is the same share/session key, so an image rides the exact same
 * secrecy boundary as the rest of the payload: the Worker only ever sees the
 * opaque result and the key never leaves the device.
 */
export async function encryptBytes(key: CryptoKey, data: ArrayBuffer): Promise<Uint8Array<ArrayBuffer>> {
  const iv = crypto.getRandomValues(new Uint8Array(IV_LENGTH_BYTES));
  const ciphertext = await crypto.subtle.encrypt({ name: 'AES-GCM', iv }, key, data);
  // `new Uint8Array(number)` is concretely ArrayBuffer-backed (not SharedArrayBuffer),
  // so the result is a clean BodyInit/BlobPart for the R2 upload at the boundary.
  const combined = new Uint8Array(IV_LENGTH_BYTES + ciphertext.byteLength);
  combined.set(iv, 0);
  combined.set(new Uint8Array(ciphertext), IV_LENGTH_BYTES);
  return combined;
}

export async function decryptBytes(key: CryptoKey, combined: Uint8Array): Promise<ArrayBuffer | null> {
  try {
    const iv = combined.subarray(0, IV_LENGTH_BYTES);
    const ciphertext = combined.subarray(IV_LENGTH_BYTES);
    return await crypto.subtle.decrypt({ name: 'AES-GCM', iv: iv.slice() }, key, ciphertext.slice());
  } catch {
    return null;
  }
}
