import { bytesToBase64Url, base64UrlToBytes } from '@/domain/sync';

/**
 * DEC-103/107: end-to-end encryption for everything that crosses the
 * signaling room. The AES-GCM key is generated by the session host, travels
 * inside the QR code, and is never sent to the worker.
 */

export async function generateSessionKey(): Promise<string> {
  const key = await crypto.subtle.generateKey({ name: 'AES-GCM', length: 256 }, true, [
    'encrypt',
    'decrypt',
  ]);
  const raw = await crypto.subtle.exportKey('raw', key);
  return bytesToBase64Url(new Uint8Array(raw));
}

export async function importSessionKey(encodedKey: string): Promise<CryptoKey> {
  const bytes = base64UrlToBytes(encodedKey);
  return crypto.subtle.importKey('raw', bytes.buffer as ArrayBuffer, { name: 'AES-GCM' }, false, [
    'encrypt',
    'decrypt',
  ]);
}

const IV_LENGTH_BYTES = 12;

export async function encryptText(key: CryptoKey, plaintext: string): Promise<string> {
  const iv = crypto.getRandomValues(new Uint8Array(IV_LENGTH_BYTES));
  const ciphertext = await crypto.subtle.encrypt(
    { name: 'AES-GCM', iv },
    key,
    new TextEncoder().encode(plaintext),
  );
  const combined = new Uint8Array(IV_LENGTH_BYTES + ciphertext.byteLength);
  combined.set(iv, 0);
  combined.set(new Uint8Array(ciphertext), IV_LENGTH_BYTES);
  return bytesToBase64Url(combined);
}

export async function decryptText(key: CryptoKey, encoded: string): Promise<string | null> {
  try {
    const combined = base64UrlToBytes(encoded);
    const iv = combined.subarray(0, IV_LENGTH_BYTES);
    const ciphertext = combined.subarray(IV_LENGTH_BYTES);
    const plaintext = await crypto.subtle.decrypt(
      { name: 'AES-GCM', iv: iv.slice() },
      key,
      ciphertext.slice().buffer as ArrayBuffer,
    );
    return new TextDecoder().decode(plaintext);
  } catch {
    return null;
  }
}
